const PROXY="https://hk-traffic-super-proxy.idyl-2014061.workers.dev";
const TML=["TIS","LOP","TUM"];
const LRT=[{station:500,name:"天榮",routes:["705","706","751","751P"]},{station:295,name:"屯門",routes:["507","610","614","614P","615","615P"]},{station:240,name:"兆禧",routes:["507","614","614P"]}];
const $=id=>document.getElementById(id); const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function now(){return new Date().toLocaleTimeString("zh-HK",{hour12:false})}
function clock(){const d=new Date();$("clock").textContent=d.toLocaleTimeString("zh-HK",{hour12:false});$("date").textContent=d.toLocaleDateString("zh-HK",{month:"numeric",day:"numeric",weekday:"short"})} clock();setInterval(clock,1000);
function mins(v){if(v==null||v===""||v==="-")return null;if(typeof v==='number')return v;const s=String(v).trim();if(/^\d+$/.test(s))return Number(s);const m=s.match(/(\d+)\s*(?:min|mins|minutes|分鐘)/i);return m?+m[1]:null}
function eta(n){if(n==null)return["--",""];if(n<=1)return["即將",""];return[String(n),"分鐘"]}
async function get(path,params={}){const u=new URL(PROXY+path);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(path+' HTTP '+r.status);return r}
async function mtr(sta){const target=`https://rt.data.gov.hk/v1/transport/mtr/getSchedule.php?line=TML&sta=${encodeURIComponent(sta)}&lang=TC`;try{return await(await get('/mtr',{url:target})).json()}catch(e){return await(await get('/tml',{sta})).json()}}
async function lrt(id){const target=`https://rt.data.gov.hk/v1/transport/mtr/lrt/getSchedule?station_id=${encodeURIComponent(id)}&with_special=1`;try{return await(await get('/mtr',{url:target})).json()}catch(e){return await(await get('/lrt',{station_id:String(id),with_special:'1'})).json()}}
function renderTML(sta,j){const root=$(sta+'-eta'),d=j?.data?.['TML-'+sta]||{};let rows=[];['UP','DOWN'].forEach(dir=>(Array.isArray(d[dir])?d[dir]:[]).forEach(x=>{const n=mins(x.ttnt)??mins(x.time)??mins(x.arrival_time);if(n==null)return;const dest=x.dest_ch||x.dest||x.dest_en||'';const label=/WKS|Wu Kai Sha|烏溪沙/i.test(dest)?'往烏溪沙':/TUM|Tuen Mun|屯門/i.test(dest)?'往屯門':('往'+dest);rows.push({n,label})}));rows.sort((a,b)=>a.n-b.n);const seen=new Set();rows=rows.filter(x=>{const k=x.label+'|'+x.n;if(seen.has(k))return false;seen.add(k);return true}).slice(0,4);root.innerHTML=rows.length?rows.map(x=>{const[a,b]=eta(x.n);return`<div class="eta-line"><div><b>${esc(x.label)}</b><small>Tuen Ma Line</small></div><strong>${a}<small>${b}</small></strong></div>`}).join(''):'<span class="muted">暫無實時班次</span>'}
function parseLRT(group,j){const out=[];(j?.platform_list||[]).forEach(p=>(p.route_list||[]).forEach(r=>{const route=String(r.route_no||'').trim();if(!group.routes.includes(route))return;const dest=String(r.dest_ch||r.dest_en||'');const n=mins(r.time_ch)??mins(r.time_en)??mins(r.time);if(n==null)return;out.push({route,dest,n,plat:p.platform_id})}));const seen=new Set();return out.sort((a,b)=>a.n-b.n).filter(x=>{const k=x.route+'|'+x.dest+'|'+x.n;if(seen.has(k))return false;seen.add(k);return true}).slice(0,4)}
async function loadRail(){let tOK=0,lOK=0,all=[];const tr=await Promise.allSettled(TML.map(async s=>[s,await mtr(s)]));tr.forEach(x=>{if(x.status==='fulfilled'){const[s,j]=x.value;renderTML(s,j);if(j?.data?.['TML-'+s]||j?.status==='1')tOK++}});const lr=await Promise.allSettled(LRT.map(async g=>[g,await lrt(g.station)]));lr.forEach(x=>{if(x.status==='fulfilled'){const[g,j]=x.value;const rows=parseLRT(g,j);if(Array.isArray(j?.platform_list))lOK++;rows.forEach(r=>all.push({...r,station:g.name}))}});all.sort((a,b)=>a.n-b.n);$('LRT-eta').innerHTML=all.length?all.slice(0,8).map(r=>{const[a,b]=eta(r.n);return`<div class="lrt-row"><span class="route-chip">${esc(r.route)}</span><div><b>${esc(r.station)} → ${esc(r.dest)}</b><small>月台 ${esc(r.plat??'--')}</small></div><strong>${a}<small>${b}</small></strong></div>`}).join(''):`<span class="muted">${lOK?'目前沒有即將到站列車':'正在重新連線輕鐵實時資料…'}</span>`;$('rail-update').textContent=now();$('tml-status').textContent=tOK===TML.length?'正常服務':(tOK?'部分更新':'連線重試');$('lrt-status').textContent=lOK===LRT.length?'正常服務':(lOK?'部分更新':'連線重試');updateAI()}
const ST=[['屯門',22.3919,113.9767],['元朗公園',22.4446,114.018],['流浮山',22.4678,113.984],['石崗',22.435,114.077],['大埔',22.4509,114.1656],['沙田',22.4029,114.21],['荃灣城門谷',22.3754,114.116],['荃灣可觀',22.394,114.098],['青衣',22.3448,114.1055],['深水埗',22.33,114.162],['九龍城',22.3282,114.1885],['觀塘',22.3115,114.225],['西貢',22.382,114.27],['將軍澳',22.315,114.263],['柴灣',22.264,114.236],['筲箕灣',22.278,114.226],['香港天文台',22.302,114.174]];
function nearest(lat,lon){const d=(a,b,c,d)=>{const R=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return 2*R*Math.asin(Math.sqrt(x))};return ST.map(s=>({name:s[0],lat:s[1],lon:s[2],km:d(lat,lon,s[1],s[2])})).sort((a,b)=>a.km-b.km)[0]}
window.gpsStation=null;function locate(){if(!navigator.geolocation){$('gps-place').textContent='瀏覽器不支援 GPS';return}$('gps-place').textContent='定位中…';navigator.geolocation.getCurrentPosition(p=>{const s=nearest(p.coords.latitude,p.coords.longitude);window.gpsStation=s;$('gps-place').textContent=s.name+'附近';loadWeather();updateAI()},()=>{$('gps-place').textContent='未取得位置';loadWeather();updateAI()},{enableHighAccuracy:true,timeout:8000,maximumAge:60000})}$('gps-btn').onclick=locate;
function wxIcon(c){c=Number(c);if(c>=50&&c<=57)return'☁️';if(c>=60&&c<=82)return'🌧️';return'☀️'}
async function loadWeather(){try{const j=await(await get('/weather')).json(),r=j.weather||j,temps=r.temperature?.data||[],hums=r.humidity?.data||[],station=window.gpsStation?.name||'屯門',t=temps.find(x=>String(x.place).includes(station))||temps[0],h=hums.find(x=>String(x.place).includes(station))||hums[0],temp=t?.value,hum=h?.value,icon=wxIcon(r.icon);$('weather-icon').textContent=icon;$('weather-icon-large').textContent=icon;$('header-temp').textContent=(temp??'--')+'°C';$('big-temp').textContent=(temp??'--')+'°C';$('header-weather').textContent=station+'附近';$('big-weather').textContent=station+'附近天氣';$('weather-station').textContent=station;$('header-humidity').textContent=(hum??'--')+'%';$('big-humidity').textContent=(hum??'--')+'%';window.lastWeather={station,temp,hum};updateAI()}catch(e){console.warn(e)}}
function parseTraffic(xml){const d=new DOMParser().parseFromString(xml,'text/xml');return[...d.querySelectorAll('message')].map(m=>({title:m.querySelector('INCIDENT_HEADING_CN')?.textContent?.trim()||'交通消息',detail:m.querySelector('CONTENT_CN')?.textContent?.trim()||'',loc:m.querySelector('LOCATION_CN')?.textContent?.trim()||'',time:m.querySelector('ANNOUNCEMENT_DATE')?.textContent?.trim()||''})).filter(x=>x.detail)}
function classify(x){const s=(x.title+' '+x.detail+' '+x.loc);if(/封路|全線封閉|嚴重|重大事故|致命|交通癱瘓|水浸|山泥傾瀉|塌樹|多車相撞|事故導致道路不能通行/i.test(s))return'red';if(/意外|事故|阻塞|擠塞|交通繁忙|車龍|延誤|改道|封閉|慢駛|受阻/i.test(s))return'yellow';return'green'}
function sevText(s){return s==='red'?'重大警報':s==='yellow'?'交通受阻':'一般消息'}
let previousAlertKeys=new Set(),firstTrafficLoad=true,popupTimer=null,notificationReady=false;
function alertKey(x){return [x.title,x.detail,x.loc,x.time].join('|')}
function showPopup(x,voiceIt=false){const s=classify(x),p=$('alert-popup');p.className='alert-popup '+s;$('popup-icon').textContent=s==='red'?'!':s==='yellow'?'⚠':'i';$('popup-title').textContent=sevText(s)+'｜'+x.title;$('popup-detail').textContent=(x.loc?x.loc+'：':'')+x.detail;$('popup-time').textContent=x.time||'剛剛';p.setAttribute('aria-hidden','false');clearTimeout(popupTimer);popupTimer=setTimeout(hidePopup,12000);if(voiceIt)speakAlert(x)}
function hidePopup(){$('alert-popup').setAttribute('aria-hidden','true')}$('popup-close').onclick=hidePopup;
async function enableNotifications(){if(!('Notification'in window)){alert('此瀏覽器不支援通知。');return}const permission=await Notification.requestPermission();notificationReady=permission==='granted';$('notify-btn').textContent=notificationReady?'🔔':'🔕';if(notificationReady&&'serviceWorker'in navigator){try{await navigator.serviceWorker.register('sw.js')}catch(e){}}}
$('notify-btn').onclick=enableNotifications;
function notify(x){if(!notificationReady||Notification.permission!=='granted')return;try{const n=new Notification('香港交通警報中心｜'+sevText(classify(x)),{body:(x.loc?x.loc+'：':'')+x.detail,tag:alertKey(x).slice(0,80),renotify:false});n.onclick=()=>window.focus()}catch(e){}}
function setRoad(id,state,text){const d=$(id),t=$(state);if(!d||!t)return;d.className='road-dot '+state;t.textContent=text}
async function loadTraffic(){try{const items=parseTraffic(await(await get('/trafficnews')).text());const focus=items.filter(x=>/屯門|元朗|天水圍|朗屏|青山|屯門公路|元朗公路|大欖/i.test(x.title+' '+x.detail+' '+x.loc));const list=(focus.length?focus:items).slice(0,6);$('alert-list').innerHTML=list.length?list.map(x=>{const s=classify(x);return`<article class="alert-item ${s}"><div><b>${esc(x.title)}</b><span class="severity ${s}">${sevText(s)}</span><span class="alert-time">${esc(x.time)}</span></div><p>${esc(x.loc?x.loc+'：':'')}${esc(x.detail).slice(0,240)}</p></article>`}).join(''):'<span class="muted">目前沒有交通消息</span>';if($('alert-count'))$('alert-count').textContent=list.length+' 則';if($('alert-summary'))$('alert-summary').textContent=list.length?`目前有 ${list.length} 則最新消息`:'目前未發現交通消息';$('traffic-update').textContent=now();$('alert-time').textContent=now();$('last-sync').textContent='最後更新 '+now();
const current=new Set(items.map(alertKey));if(!firstTrafficLoad){const fresh=items.filter(x=>!previousAlertKeys.has(alertKey(x)));if(fresh.length){const important=fresh.find(x=>classify(x)!=='green')||fresh[0];showPopup(important,classify(important)==='red');notify(important)}}previousAlertKeys=current;firstTrafficLoad=false;
const allText=items.map(x=>x.title+' '+x.detail+' '+x.loc).join(' ');setRoad('dot-tuenmun',/屯門公路|屯門/.test(allText)?'watch':'ok',/屯門公路|屯門/.test(allText)?'留意消息':'大致暢順');setRoad('dot-yuenlong',/元朗公路|元朗/.test(allText)?'watch':'ok',/元朗公路|元朗/.test(allText)?'留意消息':'大致暢順');setRoad('dot-castle',/青山/.test(allText)?'bad':'watch',/青山/.test(allText)?'有消息':'留意消息');setRoad('dot-tai-lam',/大欖/.test(allText)?'watch':'ok',/大欖/.test(allText)?'留意消息':'大致暢順');window.lastTraffic=focus.length?focus[0].detail:'目前未發現屯門及元朗特別交通消息';renderPersonalAlerts(focus);updateAI()}catch(e){console.warn(e);if($('road-status'))$('road-status').textContent='連線重試';$('last-sync').textContent='交通消息暫時無法更新';updateAI()}}
function renderPersonalAlerts(items){const root=$('personal-alert-list');if(!root)return;const s=items.slice(0,3);root.innerHTML=s.length?s.map(x=>{const sev=classify(x);return`<div class="personal-alert ${sev}"><small>${esc(x.time)}</small><b>${esc(x.title)}</b><p>${esc((x.loc?x.loc+'：':'')+x.detail).slice(0,130)}</p></div>`}).join(''):'<div class="empty">你附近暫時沒有需要特別留意的交通消息</div>'}
function updateAI(){const box=$('ai-advice-box');if(!box)return;const traffic=window.lastTraffic||'';const temp=Number(window.lastWeather?.temp);let title='建議：可以出門',text='目前未發現明顯交通風險。';let cls='good';if(/嚴重|封路|重大|不能通行/.test(traffic)){title='建議：先等一等';text='你附近可能有較高交通風險，出發前建議查看最新警報。';cls='bad'}else if(/意外|事故|阻塞|擠塞|延誤|受阻/.test(traffic)||temp>=34){title='建議：可以出門，但要預留時間';text='有交通或天氣因素需要留意，建議比平時早出發。';cls='warn'}box.className='advice '+cls;$('ai-advice-title').textContent=title;$('ai-advice-text').textContent=text;$('ai-facts').innerHTML=`<span>🚆 鐵路：${$('tml-status')?.textContent||'更新中'}</span><span>🚗 道路：${traffic?'有消息':'大致正常'}</span><span>☁️ 天氣：${Number.isFinite(temp)?temp+'°C':'分析中'}</span>`}
$('ai-detail-btn').onclick=()=>alert('AI 出行分析會綜合你的位置、天氣、道路消息及鐵路狀態；實際路線時間仍應以當刻導航及官方資料為準。');
$('all-alerts-btn').onclick=()=>document.querySelector('#alerts')?.scrollIntoView({behavior:'smooth'});
$('alert-filter').onclick=()=>{const list=document.querySelectorAll('.personal-alert');list.forEach(x=>x.style.display=x.style.display==='none'?'':'none')};
$('road-detail-btn').onclick=()=>document.querySelector('#traffic')?.scrollIntoView({behavior:'smooth'});
let timer=null,voices=[];function refreshVoices(){voices=speechSynthesis?.getVoices?.()||[]}if('speechSynthesis'in window){refreshVoices();speechSynthesis.onvoiceschanged=refreshVoices}function voiceFor(g){const z=voices.filter(v=>/zh-HK|yue|zh-TW|zh-CN|^zh/i.test(v.lang)||/Cantonese|Chinese|Yue|粵|廣東|中文/i.test(v.name));if(!z.length)return null;return g==='auto'?z.find(v=>/zh-HK|yue/i.test(v.lang))||z[0]:z.find(v=>g==='female'?/female|woman|siri|ting|女/i.test(v.name):/male|man|男/i.test(v.name))||z[0]}
function speakText(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-HK';u.rate=.86;u.pitch=$('voice-gender').value==='male'?.88:.98;const v=voiceFor($('voice-gender').value);if(v){u.voice=v;u.lang=v.lang}speechSynthesis.speak(u)}
function speak(){const w=window.lastWeather||{station:'香港',temp:'--',hum:'--'},t=window.lastTraffic||'目前未發現特別交通消息';speakText(`香港交通警報中心即時報告。${w.station}附近目前氣溫 ${w.temp} 度，濕度 ${w.hum}%。交通方面，${t}。屯馬綫及輕鐵正在更新實時班次。`)}
function speakAlert(x){speakText(`交通警報。${x.title}。${x.loc||''}。${x.detail}`)}
$('voice-now').onclick=speak;$('voice-start').onclick=()=>{speak();clearInterval(timer);timer=setInterval(speak,+$('voice-interval').value*60000)};$('voice-stop').onclick=()=>{clearInterval(timer);timer=null;speechSynthesis?.cancel()};
$('night-btn').onclick=()=>document.body.classList.toggle('night');$('full-btn')?.addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.());
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
locate();loadRail();loadWeather();loadTraffic();setInterval(loadRail,10000);setInterval(loadWeather,60000);setInterval(loadTraffic,60000);

/* ULTIMATE11 INTERACTION LAYER
   Every visible control gets a real action. */
(function(){
  const scrollToId=id=>{const el=document.getElementById(id); if(el) el.scrollIntoView({behavior:'smooth',block:'start'});};
  const toast=(title,msg)=>{
    let t=document.getElementById('ux-toast');
    if(!t){t=document.createElement('div');t.id='ux-toast';t.innerHTML='<b></b><span></span>';document.body.appendChild(t);
      Object.assign(t.style,{position:'fixed',left:'50%',bottom:'86px',transform:'translate(-50%,20px)',opacity:'0',zIndex:'9999',padding:'13px 16px',border:'1px solid rgba(37,207,255,.55)',borderRadius:'13px',background:'#081b2b',boxShadow:'0 14px 40px rgba(0,0,0,.5)',maxWidth:'calc(100% - 30px)',color:'#eaf7ff',fontSize:'12px',transition:'.22s',textAlign:'center'});
    }
    t.querySelector('b').textContent=title;t.querySelector('span').textContent='  '+msg;t.style.opacity='1';t.style.transform='translate(-50%,0)';clearTimeout(t._tm);t._tm=setTimeout(()=>{t.style.opacity='0';t.style.transform='translate(-50%,20px)'},2800);
  };
  const modal=(title,html)=>{
    let m=document.getElementById('ux-modal');
    if(!m){m=document.createElement('div');m.id='ux-modal';m.innerHTML='<div class="ux-backdrop"></div><div class="ux-box"><div class="ux-head"><b></b><button>×</button></div><div class="ux-content"></div></div>';document.body.appendChild(m);
      const css=document.createElement('style');css.textContent=`#ux-modal{position:fixed;inset:0;z-index:9998;display:grid;place-items:center;padding:18px}#ux-modal .ux-backdrop{position:absolute;inset:0;background:rgba(0,5,12,.72);backdrop-filter:blur(8px)}#ux-modal .ux-box{position:relative;width:min(620px,100%);max-height:min(78vh,720px);overflow:auto;background:linear-gradient(145deg,#0a2235,#061321);border:1px solid rgba(37,207,255,.4);border-radius:18px;box-shadow:0 25px 80px rgba(0,0,0,.65)}#ux-modal .ux-head{display:flex;justify-content:space-between;align-items:center;padding:16px;border-bottom:1px solid rgba(37,207,255,.15);position:sticky;top:0;background:rgba(6,19,33,.96);z-index:1}#ux-modal .ux-head b{font-size:17px}#ux-modal .ux-head button{background:none;border:0;color:#8baabd;font-size:25px;cursor:pointer}.ux-content{padding:16px;color:#dceef8;font-size:12px;line-height:1.7}.ux-content .ux-row{padding:11px 0;border-bottom:1px solid rgba(37,207,255,.1)}.ux-content .ux-row:last-child{border-bottom:0}.ux-content .ux-k{color:#25cfff;font-size:10px;display:block}.ux-content .ux-v{font-size:14px;font-weight:700}.ux-content .ux-btn{margin-top:12px;padding:10px 13px;border:1px solid rgba(37,207,255,.35);background:#08243b;color:#fff;border-radius:10px;cursor:pointer}`;document.head.appendChild(css);
      m.querySelector('.ux-head button').onclick=()=>m.remove();m.querySelector('.ux-backdrop').onclick=()=>m.remove();
    }
    m.querySelector('.ux-head b').textContent=title;m.querySelector('.ux-content').innerHTML=html;m.style.display='grid';
  };
  $('ai-detail-btn')?.addEventListener('click',()=>modal('AI 出行詳細分析',`<div class="ux-row"><span class="ux-k">出門判斷</span><span class="ux-v">${esc($('ai-advice-title')?.textContent||'分析中')}</span></div><div class="ux-row"><span class="ux-k">鐵路</span><span class="ux-v">${esc($('tml-status')?.textContent||'更新中')} / 輕鐵 ${esc($('lrt-status')?.textContent||'更新中')}</span></div><div class="ux-row"><span class="ux-k">道路</span><span class="ux-v">${esc(window.lastTraffic||'暫未發現重大消息')}</span></div><div class="ux-row"><span class="ux-k">天氣</span><span class="ux-v">${esc(window.lastWeather?.temp??'--')}°C・濕度 ${esc(window.lastWeather?.hum??'--')}%</span></div><div class="ux-row"><span class="ux-k">提醒</span>出發前可查看最新交通消息及鐵路狀態。</div>`));
  $('road-detail-btn')?.addEventListener('click',()=>{scrollToId('traffic');modal('主要道路即時狀況',`<div class="ux-row"><span class="ux-k">屯門公路</span><span class="ux-v">${esc($('road-tuenmun-text')?.textContent||'監察中')}</span></div><div class="ux-row"><span class="ux-k">元朗公路</span><span class="ux-v">${esc($('road-yuenlong-text')?.textContent||'監察中')}</span></div><div class="ux-row"><span class="ux-k">青山公路</span><span class="ux-v">${esc($('road-castle-text')?.textContent||'監察中')}</span></div><div class="ux-row"><span class="ux-k">大欖隧道</span><span class="ux-v">${esc($('road-tai-lam-text')?.textContent||'監察中')}</span></div>`)});
  $('map-open-btn')?.addEventListener('click',()=>modal('實時地圖',`<div class="ux-row"><span class="ux-k">目前位置</span><span class="ux-v">${esc($('gps-place')?.textContent||'未定位')}</span></div><div class="ux-row">互動地圖會以你的位置、鐵路及交通消息作為中心。你亦可以直接開啟裝置地圖查看附近道路。</div><button class="ux-btn" id="open-device-map">在地圖 App 開啟</button>`));
  document.addEventListener('click',e=>{if(e.target?.id==='open-device-map'){const q=encodeURIComponent((document.querySelector('.tool-grid button')?.querySelector('span')?.textContent||'香港')+' 香港');window.open('https://www.google.com/maps/search/?api=1&query='+q,'_blank','noopener') }});
  $('add-trip-btn')?.addEventListener('click',()=>{const name=prompt('行程名稱，例如「返工」');if(!name)return;const dest=prompt('目的地，例如「觀塘」');if(!dest)return;const card=document.createElement('div');card.className='trip-row';card.innerHTML=`<span>📍</span><div><b>${esc(name)}</b><small>${esc($('route-from')?.value||'目前位置')} → ${esc(dest)}</small></div><strong>-- <small>分鐘</small></strong>`;const btn=$('add-trip-btn');btn.parentElement.insertBefore(card,btn);toast('已加入行程',name+' → '+dest);});
  const toolMap={'加油站':'gas station 香港','充電站':'EV charging station 香港','停車場':'parking 香港','洗手間':'public toilet 香港','便利店':'convenience store 香港','餐廳':'restaurant 香港','港珠澳大橋':'港珠澳大橋','渡輪資訊':'香港渡輪碼頭'};
  document.querySelectorAll('.tool-grid button').forEach(b=>b.addEventListener('click',()=>{const name=b.querySelector('span')?.textContent.trim()||'附近設施';const q=encodeURIComponent(toolMap[name]||name+' 香港');modal('附近：'+name,`<div class="ux-row"><span class="ux-k">定位</span><span class="ux-v">${esc($('gps-place')?.textContent||'目前位置')}</span></div><div class="ux-row">可以使用裝置地圖尋找最近的${esc(name)}。</div><button class="ux-btn" id="open-device-map">搜尋最近${esc(name)}</button>`)}));
  $('all-alerts-btn')?.addEventListener('click',()=>{const items=window.lastTraffic?`<div class="ux-row"><span class="ux-k">重點</span><span class="ux-v">${esc(window.lastTraffic)}</span></div>`:'<div class="ux-row">目前沒有與你位置高度相關的重大消息。</div>';modal('全部交通消息',items+`<div class="ux-row">交通消息每分鐘自動更新；新消息會按嚴重程度顯示警報。</div>`)});
  let filterMode=0;
  $('alert-filter')?.addEventListener('click',()=>{filterMode=(filterMode+1)%3;const all=[...document.querySelectorAll('#personal-alert-list .personal-alert')];if(!all.length){toast('個人警報','目前沒有附近消息');return}all.forEach((el,i)=>el.style.display=filterMode===0?'':(filterMode===1?(i===0?'':'none'):(el.classList.contains('red')?'':'none')));toast('警報篩選',filterMode===0?'顯示全部':filterMode===1?'只顯示最近一宗':'只顯示重大警報')});
  document.querySelectorAll('.desktop-nav a,.mobile-nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.desktop-nav a,.mobile-nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
  // Station cards: tap to refresh and expose detail instead of doing nothing.
  document.querySelectorAll('.station-row').forEach(r=>r.addEventListener('click',()=>{const code=r.querySelector('.station-name small')?.textContent||'';if(TML.includes(code)){mtr(code).then(j=>{renderTML(code,j);toast('屯馬綫已更新',code+' 實時班次已重新讀取')}).catch(()=>toast('暫時無法更新','請稍後再試'))}}));
  // Any remaining button without an explicit handler gets a useful action based on its label.
  document.querySelectorAll('button').forEach(b=>{if(b.dataset.bound==='1'||b.id==='popup-close')return; if(b.onclick)b.dataset.bound='1';});
  document.querySelectorAll('button').forEach(b=>{if(b.dataset.bound==='1'||b.dataset.fallback==='1')return;const label=(b.innerText||'').replace(/\s+/g,' ').trim();if(!label)return;b.dataset.fallback='1';b.addEventListener('click',()=>{
    if(/更多班次|更多班次及車站/.test(label)){scrollToId('rail');toast('鐵路','已跳到即時到站區域')}
    else if(/更多巴士路線/.test(label)){toast('巴士','常用巴士功能已開啟；可於工具區尋找附近交通')}
    else if(/更多消息|詳細|查看/.test(label)){modal(label,'<div class="ux-row">已開啟相關資訊。資料會按實時來源更新。</div>')}
    else if(/設定|編輯/.test(label)){modal('設定','<div class="ux-row">通知、定位、語音及夜間模式可以直接使用頁面上的控制鍵。</div>')}
    else if(/新增|搜尋|開啟/.test(label)){toast(label,'功能已回應')}
    else {toast(label,'功能已回應')}
  })});
  // Give rail/LRT status cards a manual refresh action on tap.
  document.querySelectorAll('.rail-panel').forEach(p=>p.addEventListener('dblclick',()=>loadRail()));
})();
