const PROXY="https://hk-traffic-super-proxy.idyl-2014061.workers.dev";
const TML=["TIS","LOP","TUM"];
const LRT=[{station:500,name:"天榮",routes:["705","706","751","751P"]},{station:295,name:"屯門",routes:["507","610","614","614P","615","615P"]},{station:240,name:"兆禧",routes:["507","614","614P"]}];
const $=id=>document.getElementById(id); const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function clock(){const d=new Date();$("clock").textContent=d.toLocaleTimeString("zh-HK",{hour12:false});$("date").textContent=d.toLocaleDateString("zh-HK",{month:"numeric",day:"numeric",weekday:"short"})} clock(); setInterval(clock,1000);
function mins(v){if(v==null||v===""||v==="-")return null;if(typeof v==='number')return v;const s=String(v).trim();if(/^\d+$/.test(s))return Number(s);const m=s.match(/(\d+)\s*(?:min|mins|minutes|分鐘)/i);if(m)return +m[1];return null}
function eta(n){if(n==null)return ["--",""];if(n<=1)return ["即將",""];return [String(n),"分鐘"]}
async function get(path,params={}){const u=new URL(PROXY+path);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(path+' HTTP '+r.status);return r}
async function mtr(sta){return (await get('/tml',{sta})).json()}
async function lrt(id){return (await get('/lrt',{station_id:String(id),with_special:'1'})).json()}
function renderTML(sta,j){const root=$(sta+'-eta');const d=j?.data?.['TML-'+sta]||{};let rows=[];['UP','DOWN'].forEach(dir=>{(Array.isArray(d[dir])?d[dir]:[]).forEach(x=>{const n=mins(x.ttnt)??mins(x.time)??mins(x.arrival_time);if(n==null)return;const dest=x.dest_ch||x.dest||x.dest_en||'';const label=/WKS|Wu Kai Sha|烏溪沙/i.test(dest)?'往烏溪沙':/TUM|Tuen Mun|屯門/i.test(dest)?'往屯門':('往'+dest);rows.push({n,label})})});rows.sort((a,b)=>a.n-b.n);const seen=new Set();rows=rows.filter(x=>{const k=x.label+'|'+x.n;if(seen.has(k))return false;seen.add(k);return true}).slice(0,4);root.innerHTML=rows.length?rows.map(x=>{const[a,b]=eta(x.n);return `<div class="eta-line"><div><b>${esc(x.label)}</b><small>Tuen Ma Line</small></div><strong>${a}<small>${b}</small></strong></div>`}).join(''):'<span class="muted">暫無實時班次</span>'}
function parseLRT(group,j){const out=[];(j?.platform_list||[]).forEach(p=>(p.route_list||[]).forEach(r=>{const route=String(r.route_no||'').trim();if(!group.routes.includes(route))return;const dest=String(r.dest_ch||r.dest_en||'');const n=mins(r.time_ch)??mins(r.time_en)??mins(r.time);if(n==null)return;out.push({route,dest,n,plat:p.platform_id})}));const seen=new Set();return out.sort((a,b)=>a.n-b.n).filter(x=>{const k=x.route+'|'+x.dest+'|'+x.n;if(seen.has(k))return false;seen.add(k);return true}).slice(0,4)}
async function loadRail(){let tOK=0,lOK=0,all=[];const tr=await Promise.allSettled(TML.map(async s=>[s,await mtr(s)]));tr.forEach(x=>{if(x.status==='fulfilled'){const[s,j]=x.value;renderTML(s,j);if(j?.status==='1'||j?.data?.['TML-'+s])tOK++}else console.warn(x.reason)});const lr=await Promise.allSettled(LRT.map(async g=>[g,await lrt(g.station)]));lr.forEach(x=>{if(x.status==='fulfilled'){const[g,j]=x.value;const rows=parseLRT(g,j);if(Array.isArray(j?.platform_list))lOK++;rows.forEach(r=>all.push({...r,station:g.name}))}else console.warn(x.reason)});all.sort((a,b)=>a.n-b.n);$('LRT-eta').innerHTML=all.length?all.slice(0,8).map(r=>{const[a,b]=eta(r.n);return `<div class="lrt-row"><span class="route-chip">${esc(r.route)}</span><div><b>${esc(r.station)} → ${esc(r.dest)}</b><small>月台 ${esc(r.plat??'--')}</small></div><strong>${a}<small>${b}</small></strong></div>`}).join(''):'<span class="muted">目前沒有即將到站列車</span>';$('rail-update').textContent=new Date().toLocaleTimeString('zh-HK',{hour12:false});$('tml-status').textContent=tOK?'正常服務':'連線重試';$('lrt-status').textContent=lOK?'正常服務':'連線重試'}
const ST=[['屯門',22.3919,113.9767],['元朗公園',22.4446,114.018],['流浮山',22.4678,113.984],['石崗',22.435,114.077],['大埔',22.4509,114.1656],['沙田',22.4029,114.21],['荃灣城門谷',22.3754,114.116],['荃灣可觀',22.394,114.098],['青衣',22.3448,114.1055],['深水埗',22.33,114.162],['九龍城',22.3282,114.1885],['觀塘',22.3115,114.225],['西貢',22.382,114.27],['將軍澳',22.315,114.263],['柴灣',22.264,114.236],['筲箕灣',22.278,114.226],['香港天文台',22.302,114.174]];
function nearest(lat,lon){const d=(a,b,c,d)=>{const R=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return 2*R*Math.asin(Math.sqrt(x))};return ST.map(s=>({name:s[0],lat:s[1],lon:s[2],km:d(lat,lon,s[1],s[2])})).sort((a,b)=>a.km-b.km)[0]}
window.gpsStation=null; function locate(){if(!navigator.geolocation){$('gps-place').textContent='瀏覽器不支援 GPS';return}$('gps-place').textContent='定位中…';navigator.geolocation.getCurrentPosition(p=>{const s=nearest(p.coords.latitude,p.coords.longitude);window.gpsStation=s;$('gps-place').textContent=s.name+'附近';loadWeather()},()=>{$('gps-place').textContent='未取得位置';loadWeather()},{enableHighAccuracy:true,timeout:8000,maximumAge:60000})}$('gps-btn').onclick=locate;
function wxIcon(c){c=Number(c);if(c>=50&&c<=57)return'☁️';if(c>=60&&c<=82)return'🌧️';return'☀️'}
async function loadWeather(){try{const j=await(await get('/weather')).json();const r=j.weather||j,temps=r.temperature?.data||[],hums=r.humidity?.data||[],station=window.gpsStation?.name||'屯門';const t=temps.find(x=>String(x.place).includes(station))||temps[0],h=hums.find(x=>String(x.place).includes(station))||hums[0],temp=t?.value,hum=h?.value,icon=wxIcon(r.icon);$('weather-icon').textContent=icon;$('weather-icon-large').textContent=icon;$('header-temp').textContent=(temp??'--')+'°C';$('big-temp').textContent=(temp??'--')+'°C';$('header-weather').textContent=station+'附近';$('big-weather').textContent=station+'附近天氣';$('weather-station').textContent=station;$('header-humidity').textContent=(hum??'--')+'%';$('big-humidity').textContent=(hum??'--')+'%';window.lastWeather={station,temp,hum}}catch(e){console.warn(e)}}
function parseTraffic(xml){const d=new DOMParser().parseFromString(xml,'text/xml');return [...d.querySelectorAll('message')].map(m=>({title:m.querySelector('INCIDENT_HEADING_CN')?.textContent?.trim()||'交通消息',detail:m.querySelector('CONTENT_CN')?.textContent?.trim()||'',loc:m.querySelector('LOCATION_CN')?.textContent?.trim()||'',time:m.querySelector('ANNOUNCEMENT_DATE')?.textContent?.trim()||''})).filter(x=>x.detail)}
async function loadTraffic(){try{const items=parseTraffic(await(await get('/trafficnews')).text());const focus=items.filter(x=>/屯門|元朗|天水圍|朗屏|青山|屯門公路|元朗公路|大欖/i.test(x.title+' '+x.detail+' '+x.loc));const list=(focus.length?focus:items).slice(0,4);$('alert-list').innerHTML=list.length?list.map(x=>`<article class="alert-item"><div><b>${esc(x.title)}</b><span class="alert-time">${esc(x.time)}</span></div><p>${esc(x.loc?x.loc+'：':'')}${esc(x.detail).slice(0,190)}</p></article>`).join(''):'<span class="muted">目前沒有交通消息</span>';$('alert-count').textContent=list.length+' 則';$('road-status').textContent=focus.length?'留意消息':'大致暢順';$('road-tuenmun-text').textContent=focus.length?'留意消息':'大致暢順';$('traffic-update').textContent=new Date().toLocaleTimeString('zh-HK',{hour12:false});$('alert-time').textContent=new Date().toLocaleTimeString('zh-HK',{hour12:false});window.lastTraffic=focus.length?focus[0].detail:'目前未發現屯門及元朗特別交通消息'}catch(e){console.warn(e);$('road-status').textContent='連線重試'}}
let timer=null,voices=[];function refreshVoices(){voices=speechSynthesis?.getVoices?.()||[]}if('speechSynthesis'in window){refreshVoices();speechSynthesis.onvoiceschanged=refreshVoices}function voiceFor(g){const z=voices.filter(v=>/zh-HK|yue|zh-TW|zh-CN|^zh/i.test(v.lang)||/Cantonese|Chinese|Yue|粵|廣東|中文/i.test(v.name));if(!z.length)return null;return g==='auto'?z.find(v=>/zh-HK|yue/i.test(v.lang))||z[0]:z.find(v=>g==='female'?/female|woman|siri|ting|女/i.test(v.name):/male|man|男/i.test(v.name))||z[0]}
function speak(){if(!('speechSynthesis'in window))return;const w=window.lastWeather||{station:'香港',temp:'--',hum:'--'},t=window.lastTraffic||'目前未發現特別交通消息';speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`香港交通控制中心即時報告。${w.station}附近目前氣溫 ${w.temp} 度，濕度 ${w.hum}%。交通方面，${t}。屯馬綫及輕鐵正在更新實時班次。`);u.lang='zh-HK';u.rate=.86;u.pitch=$('voice-gender').value==='male'?.88:.98;const v=voiceFor($('voice-gender').value);if(v){u.voice=v;u.lang=v.lang}speechSynthesis.speak(u)}
$('voice-now').onclick=speak;$('voice-start').onclick=()=>{speak();clearInterval(timer);timer=setInterval(speak,+$('voice-interval').value*60000)};$('voice-stop').onclick=()=>{clearInterval(timer);timer=null;speechSynthesis?.cancel()};$('night-btn').onclick=()=>document.body.classList.toggle('night');$('full-btn').onclick=()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();
locate();loadRail();loadWeather();loadTraffic();setInterval(loadRail,10000);setInterval(loadWeather,60000);setInterval(loadTraffic,60000);